'use strict';
const ff=document.querySelector('#ff'),sl=document.querySelector('#sl'),videos=[ff,sl];
let view='crop',speed='slow_5x',playing=false;
const play=document.querySelector('#play'),slider=document.querySelector('#frame'),label=document.querySelector('#frame-label');
function timeForFrame(i){return i*(speed==='slow_5x'?5:1)*1001/60000;}
function updateFrame(){const i=Math.min(15,Math.round(ff.currentTime/(1001/60000*(speed==='slow_5x'?5:1))));slider.value=i;label.textContent=`${String(i+1).padStart(2,'0')} / 16 · ${(trajectories.ff_base.rows[i].t*1000).toFixed(0)} ms`;}
function pause(){playing=false;videos.forEach(v=>v.pause());play.textContent='▶ Play both';}
async function start(){if(ff.readyState<2||sl.readyState<2)return;sl.currentTime=ff.currentTime;try{await Promise.all(videos.map(v=>v.play()));playing=true;play.textContent='Ⅱ Pause both';}catch(e){pause();document.querySelector('#view-caption').textContent='Playback could not start. Press Play both after the videos finish loading.';}}
function frameTo(i){pause();videos.forEach(v=>{if(v.readyState>=1)v.currentTime=timeForFrame(i);});updateFrame();}
function setSources(){pause();document.body.classList.toggle('full-scene',view==='composite');videos.forEach((v,i)=>{v.src=`${i?'sl_variant':'ff_base'}_${view}_${speed}.mp4`;v.load();});slider.value=0;label.textContent='01 / 16 · 0 ms';document.querySelector('#view-caption').textContent=(view==='crop'?'Final composite · 144 × 144 ball-region crop, enlarged to 576 × 576.':view==='composite'?'Final composite · full 1280 × 720 broadcast scene.':'Raw neural output · 384 × 384 conditioning region; before background compositing.')+(speed==='slow_5x'?' 5× slow playback; 16 original generated frames.':' Original frame timing; approximately 0.267 s per loop.');}
play.addEventListener('click',()=>playing?pause():start());document.querySelector('#restart').addEventListener('click',()=>{frameTo(0);start();});slider.addEventListener('input',()=>frameTo(Number(slider.value)));
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{view=b.dataset.view;document.querySelectorAll('[data-view]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b);});setSources();}));
document.querySelectorAll('[data-speed]').forEach(b=>b.addEventListener('click',()=>{speed=b.dataset.speed;document.querySelectorAll('[data-speed]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b);});setSources();}));
ff.addEventListener('ended',()=>{if(playing){videos.forEach(v=>{v.currentTime=0;});start();}});
function tick(){if(playing){if(Math.abs(sl.currentTime-ff.currentTime)>.06&&sl.readyState>=2)sl.currentTime=ff.currentTime;updateFrame();}requestAnimationFrame(tick);}document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});setSources();tick();
const svg=document.querySelector('#trajectory-plot');
const NS='http://www.w3.org/2000/svg';function el(tag,attrs,text){const n=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));if(text)n.textContent=text;svg.appendChild(n);return n;}
function plot(caseId){svg.replaceChildren();const baseline=trajectories.ff_base.rows,edited=trajectories[caseId].rows;const all=Object.values(trajectories).flatMap(d=>d.rows);const us=all.map(r=>r.uv[0]),vs=all.map(r=>r.uv[1]);const xmin=Math.floor((Math.min(...us)-8)/10)*10,xmax=Math.ceil((Math.max(...us)+8)/10)*10,ymin=Math.floor((Math.min(...vs)-8)/10)*10,ymax=Math.ceil((Math.max(...vs)+8)/10)*10;const x=u=>65+(u-xmin)/(xmax-xmin)*505,y=v=>35+(v-ymin)/(ymax-ymin)*310;
for(let i=0;i<=4;i++){let u=xmin+(xmax-xmin)*i/4,v=ymin+(ymax-ymin)*i/4;el('line',{x1:x(u),x2:x(u),y1:35,y2:345,stroke:'#edf0f5'});el('text',{x:x(u),y:366,'text-anchor':'middle',fill:'#687489','font-size':12},u.toFixed(0));el('line',{x1:65,x2:570,y1:y(v),y2:y(v),stroke:'#edf0f5'});el('text',{x:55,y:y(v)+4,'text-anchor':'end',fill:'#687489','font-size':12},v.toFixed(0));}
el('text',{x:320,y:392,'text-anchor':'middle',fill:'#687489','font-size':12},'Image u (px) →');el('text',{x:16,y:200,transform:'rotate(-90 16 200)','text-anchor':'middle',fill:'#687489','font-size':12},'Image v (px) →');
[[baseline,'#8792a5'],[edited,'#3265cd']].forEach(([rows,color])=>{el('polyline',{points:rows.map(r=>`${x(r.uv[0])},${y(r.uv[1])}`).join(' '),fill:'none',stroke:color,'stroke-width':3,'stroke-linejoin':'round'});rows.forEach((r,i)=>el('circle',{cx:x(r.uv[0]),cy:y(r.uv[1]),r:i===15?5:2,fill:color}));});const first=baseline[0].uv;el('text',{x:x(first[0])+9,y:y(first[1])-9,fill:'#536177','font-size':12},'shared start');const a=baseline[15].uv,b=edited[15].uv,sep=Math.hypot(a[0]-b[0],a[1]-b[1]);const names={sl_variant:'Both velocity and pitch-type input change to the SL condition.',ff_slower:'All three FF velocity components are scaled by 0.98.',ff_rightward:'Only world vx increases by 0.35 m/s.',ff_upward:'Only vz increases by 0.30 m/s.'};document.querySelector('#edit-description').textContent=`${names[caseId]} Final projected separation from FF baseline: ${sep.toFixed(2)} px. Initial speed: ${trajectories[caseId].speed.toFixed(2)} m/s.`;}
document.querySelectorAll('[data-case]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-case]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b);});plot(b.dataset.case);}));plot('sl_variant');
